version: '3.4'

services:
    entitiescreator:
        container_name: entitiescreator
        image: entitiescreator
        build:
            context: ./entitiescreator
            dockerfile: EntitiesCreator.WebApp/Dockerfile
        ports:
            - "5200:443"
    entitiespresenter1:
        container_name: entitiespresenter1
        image: entitiespresenter
        build: 
            context: ./entitiespresenter
            dockerfile: Dockerfile
        ports: 
            - "4500:80"
        depends_on: 
            - entitiescreator
    entitiespresenter2:
        container_name: entitiespresenter2
        image: entitiespresenter
        build: 
            context: ./entitiespresenter
            dockerfile: Dockerfile
        ports: 
            - "4501:80"
        depends_on: 
            - entitiescreator